name: Deployment

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'

# To make Flask work
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Flask
        run: pip install Flask

      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest

# run deploy job only when job [-needs: run-tests] completed successfully
  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
             
      - name: Run deploy script
        shell: bash
        env:
          HOST_IP: ${{secrets.SERVER_IP}}
          HOST_PASSWORD: ${{secrets.SERVER_PASSWORD}}
        run: |
          chmod +x .github/scripts/deploy.sh
          .github/scripts/deploy.sh




