name: Deployment

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'

# Flask installeren
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Flask
        run: pip install Flask

# pytest installeren
      - name: Install Dependencies
        run: pip install -r requirements.txt

        # tests van test_main.py uitvoeren      
      - name: Run tests
        run: pytest

# run deploy job only when job [-needs: run-tests] completed successfully
  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
             

#      - name: install ssh keys
#        run: |
#          install -m 600 -D /dev/null ~/.ssh/id_ed25519
#          echo "${{secrets.SERVER_PRIVATEKEY}}" > ~/.ssh/id_ed25519
#          ssh-keyscan -H ${{secrets.SERVER_IP}} > ~/.ssh/known_hosts
      
      - name: Run deploy script
        env:
          HOST_IP: ${{secrets.SERVER_IP}}
          HOST_PASS: ${{secrets.SERVER_PASSWORD}}
        run: |
          chmod +x .github/scripts/deploy.sh
          .github/scripts/deploy.sh
        shell: bash

       
#      - name: remove ssh keys
#        run: rm -rf ~/.ssh


